if(CORE3D_USE_OPENGL)
    # Platform-specific OpenGL linking
    if (WIN32)
        add_subdirectory(${CMAKE_SOURCE_DIR}/thirdparty/glew ${CMAKE_BINARY_DIR}/thirdparty/glew)
        target_link_libraries(Core3D PRIVATE opengl32 GLEW)
    elseif(APPLE)
        MESSAGE(FATAL_ERROR "OpenGL backend is not supported on macOS. Please use Metal instead.")
    elseif(UNIX)
        find_package(OpenGL REQUIRED)
        add_subdirectory(${CMAKE_SOURCE_DIR}/thirdparty/glew ${CMAKE_BINARY_DIR}/thirdparty/glew)
        target_link_libraries(Core3D PRIVATE OpenGL::GL GLEW)
    endif()
endif()

# Glfw integration for window management with OpenGL
if(CORE3D_USE_OPENGL)
    # Platform-specific GLFW linking
    if(WIN32)
        add_subdirectory(${CMAKE_SOURCE_DIR}/thirdparty/glfw ${CMAKE_BINARY_DIR}/thirdparty/glfw)
        target_link_libraries(Core3D PRIVATE glfw)
    elseif(APPLE)
        MESSAGE(FATAL_ERROR "OpenGL backend is not supported on macOS. Please use Metal instead.")
    elseif(UNIX)
        find_package(glfw3 REQUIRED)
        target_link_libraries(Core3D PRIVATE glfw)
    endif()
endif()