name: CMake Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake-version: [3.24.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false  # We'll control this manually

      - name: Init submodules (Windows only)
        if: runner.os == 'Windows'
        run: git submodule update --init --recursive

      - name: Install OpenGL + GLFW (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-common-dev libglfw3-dev libglu1-mesa-dev

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: ${{ matrix.cmake-version }}

      - name: Configure CMake
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCORE3D_USE_OPENGL=OFF -DCORE3D_USE_METAL=ON -DBUILD_EXAMPLES=OFF
          else
            cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCORE3D_USE_OPENGL=ON -DBUILD_EXAMPLES=OFF
          fi
        shell: bash

      - name: Build
        run: |
          if [[ "$RUNNER_OS" == "Linux" || "$RUNNER_OS" == "macOS" ]]; then
            cmake --build build --config Release -- -j$(nproc || sysctl -n hw.ncpu || echo 2)
          else
            cmake --build build --config Release
          fi
        shell: bash

      - name: Run tests (if defined)
        run: cmake --build build --config Release
